## <font size=4>numpy.array中的运算</font>

给定一个问题, 让向量中的每一个数乘以2

a = (0,1,2)

a * 2 = (0,2,4)

In [1]:
n = 10
L = [i for i in range(n)]

In [2]:
'''
python 中 list 不支持 *2
'''
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A = []
for e in L:
    A.append(e*2)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [4]:
n = 1000000
L = [i for i in range(n)]

In [5]:
%%time
A = []
for e in L:
    A.append(e*2)

Wall time: 285 ms


明显生成表达式效率高出一截

In [6]:
%%time
A = [2*e for e in L]

Wall time: 163 ms


In [7]:
import numpy as np
L = np.arange(n)

In [10]:
%%time
A = np.array(2*e for e in L)

Wall time: 0 ns



之前在python List中, 2 * L 得到的是两个列表的拼接

在numpy.array中, 把L看做是向量, 矩阵; 直接就可以运算, 而且速度比python list 快

In [11]:
%%time
A = 2 * L

Wall time: 3.99 ms


In [12]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [13]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### <font size=3>Universal Functions: 数学方法</font>

In [20]:
X = np.arange(1, 16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [22]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [24]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [25]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [26]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [27]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [28]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [29]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [31]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [32]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [33]:
'''
对于X中的每一个元素, 都取e**x
'''
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [34]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [35]:
'''
和上面的power函数是一致的
'''
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [36]:
'''
对于X中的每一个元素求以e为底的log值
'''
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [38]:
'''
对于X中的每一个元素求以2为底的log值
'''
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [39]:
'''
对于X中的每一个元素求以10为底的log值
'''
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### <font size=3>矩阵运算</font>

In [41]:
A = np.arange(4).reshape((2, 2))
A

array([[0, 1],
       [2, 3]])

In [42]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [43]:
A + B

array([[10, 11],
       [12, 13]])

In [44]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [46]:
'''
a_ij和b_ij对应相乘的结果, 这并不是矩阵的点乘
'''
A * B

array([[ 0, 10],
       [20, 30]])

In [47]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [50]:
'''
A和B的矩阵点乘
'''
A.dot(B)

array([[10, 10],
       [50, 50]])

### <font size=3>矩阵的转置</font>

In [49]:
A

array([[0, 1],
       [2, 3]])

In [51]:
'''
行变列, 列变行
'''
A.T

array([[0, 2],
       [1, 3]])

### <font size=3>矩阵运算注意点</font>

In [53]:
C = np.full((3,3), 666)
C

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

In [54]:
'''
一个 2*2和3*3的矩阵是不能相加的
'''
A + C

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [55]:
'''
维度不同, 无法点乘
'''
A.dot(C)

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

## <font size=3>向量和矩阵进行运算</font>
### <font size=3>向量和矩阵之间的加法</font>

In [75]:
'''
一维向量
    行向量或者列向量都行, 系统是很智能的
'''
v = np.array([1, 2])
v

array([1, 2])

In [57]:
A

array([[0, 1],
       [2, 3]])

In [66]:
'''
一个向量 v 和矩阵 A 在numpy里支持这样的加法, 
但首先在数学上, 这两个东西相加是没有意义的,
不过在numpy中, 是向量和矩阵的每一行做加法

numpy会将低维的与高维减去一维的每一个元素进行运算

一个数和一个向量作加法, 就是这个数和向量中的每一个数作加法
一个向量和一个矩阵做加法, 就是这个向量和这个矩阵中的每一行相应的向量作加法
'''
v + A

array([[1, 3],
       [3, 5]])

#### <font size=3>np.vstack: 垂直堆叠</font>

In [60]:
'''
就是把v向量扩展到与A矩阵的行数一样, 堆叠两次
'''
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [65]:
'''
看看这结果, 和上面是一样的
'''

np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

#### <font size=3>np.tile: 堆叠</font>

In [64]:
'''
这个就是告诉你这个向量 v 怎么堆叠, 

在行向量上堆叠2次, 在列向量上堆叠1次

'''
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [70]:
np.tile(v, (2, 1)) + A

array([[1, 3],
       [3, 5]])

### <font size=3>向量和矩阵之间的乘法</font>

In [72]:
'''
元素之间的乘法
'''
v * A

array([[0, 2],
       [2, 6]])

#### <font size=3>.dot: 矩阵乘法</font>

In [71]:
'''
但我们需要的是矩阵间乘法

'''
v.dot(A)

array([4, 7])

In [74]:
'''
2*2的A怎么能和1*2的v做dot呢?

因为numpy将v转化为2*1

'''
A.dot(v)

array([2, 8])

 ### <font size=3>矩阵的逆</font>
 #### <font size=3>np.linalg.inv</font>
 Linear algebra: 线性代数
 
 inverse: 相反的, 逆

In [76]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [80]:
invA = np.linalg.inv(A)

In [82]:
'''
熟悉线性代数的你知道, 
对于矩阵的逆, 原矩阵和逆矩阵的点乘, 就是单位矩阵
'''
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [84]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [86]:
X = np.arange(16).reshape((2, 8))
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [89]:
'''
这个 2*8 的 X 矩阵并不能求逆, 

要求得逆矩阵的话, 最后的两个维度(当然在这里只有两个维度)必须是方阵  
'''
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

 #### <font size=3>np.linalg.pinv</font>

In [91]:
'''
数学上的解决方法:

pinv: 计算矩阵的(Moore-Penrose)伪逆。

利用矩阵的奇异值分解(SVD)计算矩阵的广义逆

'''
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [92]:
pinvX.shape

(8, 2)

In [95]:
'''
伪逆矩阵: 原矩阵X和伪逆矩阵pinv相乘, 得到对角线元素为1, 其他地方的元素几乎为0的 '伪单位矩阵', 不完全为0是计算机的浮点误差造成的 

逆矩阵和伪逆矩阵在数学上有组合更为深度的意义, 在这里不做多探讨, 在这里只了解定义

'''
X.dot(pinvX)

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])