In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
'''
原始数据
每一个样本的特征

'''
raw_data_X = [
    [3.393535321, 2.331278738],
    [3.110075348, 1.781536454],
    [1.343805883, 3.368365095],
    [3.582295404, 4.679179871],
    [2.280362544, 2.866995326],
    [7.423436594, 4.696522888],
    [5.745051997, 3.533989803],
    [9.172168622, 2.585156155],
    [7.792684984, 3.424845545],
    [7.956156488, 0.785156155],
]

'''
每一个样本的类别
'''
raw_data_y = [0,0,0,0,0,1,1,1,1,1]

In [3]:
'''
训练特征点X

训练用标签y

'''
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

In [15]:
x = np.array([8.093607318, 3.0365731514])
x

array([8.09360732, 3.03657315])

加载我们写的kNN

具体要找到自己写的代码相应的目录, 不同环境配置不同

In [5]:
% run ../../../playML/kNN.py

In [6]:
predict_y = kNN_classify(6, X_train, y_train, x)

In [7]:
'''
结果与上一小节一致
'''
predict_y

1

### <font size=3>使用scikit-learn中的kNN算法</font>

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
'''
在scikit-learn中封装的机器学习算法都是以面向对象的方式实现的, 所以首先我们需要实例化
'''
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [10]:
'''
实例化后kNN分类器对象后,我们就要执行训练fit操作, 传入训练数据集相应的特征矩阵X_train, 以及标签向量y_train 
'''
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [16]:
'''
这里报错, 因为kNN_classifier希望我们传进去的是矩阵, 而不是一个一个的数组
'''
kNN_classifier.predict(x)

ValueError: Expected 2D array, got 1D array instead:
array=[8.09360732 3.03657315].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [19]:
'''
我们改变一下, 取到待预测数据X_predict, 

reshape第一个维度:1, 第二个维度 -1 随意
'''
X_predict = x.reshape(1, -1) 

In [40]:
X_predict

array([[8.09360732, 3.03657315]])

In [18]:
'''
不报错了
'''
kNN_classifier.predict(X_predict)

array([1])

In [21]:
'''
如果需要保存结果的话, 可以存到 y_predict
'''
y_predict = kNN_classifier.predict(X_predict)

In [22]:
'''
传入样本X_predict中第0个元素预测的结果
'''
y_predict[0]

1

### <font size=3>重新整理我们的kNN算法</font>

In [45]:
%run ../../../playML/kNN-plus.py

In [46]:
knn_clf = KNNClassifier(k=6)

In [47]:
knn_clf.fit(X_train, y_train)

KNN(k=6)

In [48]:
y_predict = knn_clf.predict(X_predict)

In [49]:
'''
预测结果
'''
y_predict

array([1])

In [51]:
y_predict[0]

1

<font size=3>我们现在仿照了scikit-learn实现了我们手写的第一个kNN算法, 但是他的效果怎么样, 准确率高不高, 是我们接下来要解决的问题</font>
<br/>
<font size=3>备注: scikit-learn中的kNN是更加复杂的, 因为kNN实际上非常耗时, 所以肯定会有优化操作.</font>