### 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

### <font size=3>train test split</font>

<br/>

<font size=3>我们应该对原始数据集按照大概8:2的概率分成训练数据集和测试数据集, 测试数据集是用来测试我们通过训练数据集训练出来的模型的效果的</font>
<br/>
<font size=3>但是我们不能单纯直接取原始数据集的前80%, 因为数据集一开始里面的数据并不是均匀分布的</font>
<br/>


* 所以我们要对原始数据集进行suffle乱序处理
* 之后再取80%当做训练数据集

我们看上面iris里面的X和y是分离的, 同时也是一一对应的, 我们不能将X进行随机化, 然后再对y进行随机化

只有一起随机化, 才能保持一一对应

用numpy将X和y合并一起, 随机化之后, 再拆分成特征矩阵和标签矩阵

In [6]:
'''
标签分布不均
'''
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
'''
我们只对这 0~149 的索引进行乱序

permutation: 返回随机排列一个序列，或返回一个置换范围。

len(X): X的行数, 也就是样本的个数
'''

shuffle_indexes = np.random.permutation(len(X))

In [8]:
'''
长度和X相等 的 随机的索引序列
'''
shuffle_indexes

array([116, 136,  15,  34,  18,  47, 122,  39,  25,  29,  69,  91, 142,
       149, 139, 141,  31,  62,  57, 115,  76,  51,  61,  24,  14, 121,
        95,  37,  54, 106,  66,  20,  86,  75, 125,  46,  70,   5,   3,
       134,  50, 146,  55, 133, 118,   4,  26,  38, 119, 148, 127,  68,
        22, 147, 129,  81,  79, 114,  36, 111,  49,  63,  89, 132,  80,
        87,  40,  23, 110,  43,  21, 120,  53, 103,   0,  97,  71,  73,
       138,  92,  44, 100, 131,  60, 113, 108, 143,  48,   8, 135,  99,
       128,   1, 101, 126,  42, 145,  59,  84,  32,  52,   7,  82,  33,
        90,  35, 144, 107,  13,  16, 109,  19,  45,  78,  94, 124, 130,
        17, 105,  30,  41,  28, 104,  88,  10,  93,  58,  65, 102,   2,
        56,  12,  67,  83, 140,  11,   9, 112,  64,  98, 117,  27,   6,
        77,  72,  96, 123,  74,  85, 137])

In [9]:
'''
测试比例: 

因为有可能是浮点数, 所以取整
'''
test_ratio = 0.8
test_size = int(len(X) * test_ratio)

In [10]:
'''
这样我们就获得了测试比例的大小

'''
test_size

120

In [11]:
'''
我们取 0 ->test_size 长度的随机索引序列左右训练数据集的索引

    取 test_size -> 最后 长度的随机索引序列左右测试数据集的索引
'''
train_indexes = shuffle_indexes[:test_size]
test_indexes = shuffle_indexes[test_size:]

In [12]:
'''
只要我们获得了训练数据集的索引还有测试数据集的索引

我们就能使用 fancy indexing 来得出训练数据集和测试数据集
'''
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [13]:
'''
得出训练数据集 X_train - 矩阵

训练数据集对应的标签 y_train - 向量

'''
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [14]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### <font size=3>使用我们的算法</font>

In [15]:
import sys

# 动态添加test_package文件夹的路径，为了能让此文件夹下的
# 自定义包成功的导入
# 要根据你自己的实际包的模块来决定路径。

# sys.path.append('../')
# sys.path.append('../../')
# sys.path.append('../../../')

# 打印所有python解释器可以搜索到的所有路径
print(sys.path)

['', 'D:\\Python\\Anaconda3\\python36.zip', 'D:\\Python\\Anaconda3\\DLLs', 'D:\\Python\\Anaconda3\\lib', 'D:\\Python\\Anaconda3', 'C:\\Users\\Yukirito\\AppData\\Roaming\\Python\\Python36\\site-packages', 'D:\\Python\\Anaconda3\\lib\\site-packages', 'D:\\Python\\Anaconda3\\lib\\site-packages\\win32', 'D:\\Python\\Anaconda3\\lib\\site-packages\\win32\\lib', 'D:\\Python\\Anaconda3\\lib\\site-packages\\Pythonwin', 'D:\\Python\\Anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\Yukirito\\.ipython', '../', '../../', '../../../']


In [35]:
from playML.model_selection import train_test_split

In [36]:
'''
我们将原始的X和y传入train_test_split函数, 我们就可以直接得到X_train, X_test, y_train, y_test
'''
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [37]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [38]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [39]:
from playML.kNN import KNNClassifier

In [40]:
'''
定义一个自己的KNN分类器
'''

my_knn_clf = KNNClassifier(k=3)

In [41]:

my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [42]:
'''
将用训练数据集训练出来的KNN算法模型, 传入 测试数据集X_test, 得到结果 y_predict

'''
y_predict = my_knn_clf.predict(X_test)

In [43]:
'''
得到30个预测的对应结果
'''
y_predict

array([0, 2, 1, 1, 0, 2, 2, 1, 0, 1, 1, 2, 0, 1, 0, 1, 0, 0, 2, 2, 0, 1,
       2, 1, 2, 0, 1, 1, 1, 0])

In [44]:
'''
将测试数据集x_test的出来的预测结果y_predict和原本的标签对应的y_test进行比对
'''
y_test

array([0, 2, 1, 1, 0, 2, 2, 1, 0, 1, 2, 2, 0, 1, 0, 1, 0, 0, 2, 2, 0, 2,
       1, 1, 2, 0, 1, 1, 1, 0])

In [45]:
'''
准确率我们只要看两个中有多少元素一样就行

sum中 两个向量的比较返回的布尔值作为索引, 1表示相同, 用sum即可累加
'''
sum(y_predict == y_test)

27

In [46]:
'''
那么准确率 = 预测正确数 / 测试数据集数

我们也可以发现KNN简单的思想下, 算法非常强大 

'''
sum(y_predict == y_test)/len(y_test)

0.9

### <font size=3>scikit-learn中的train_test_split</font>

我们来看看官方库中是如何的?

In [47]:
'''
实际上和我们实现的是一样的
'''
from sklearn.model_selection import train_test_split

In [51]:
'''
我们可以发现 整个函数的设计接口是一样的

test_size=0.2 : 测试数据集所占的百分比是20%, 不写的话默认的值也是0.2

random_state=666: 随机种子
'''
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [52]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [53]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [54]:
'''
总结: 
    在机器学习中非常重要和简单的测试机器学习算法性能的方法, 
    就是将原始数据集进行train_test_split方法, 
    用train的数据集进行训练, 用test的测试集进行测试
    
    下面将用train_test_split方法来具体进行模型的选择

'''

'\n总结: \n    在机器学习中非常重要和简单的测试机器学习算法性能的方法, \n    就是将原始数据集进行train_test_split方法, \n    用train的数据集进行训练, 用test的测试集进行测试\n    \n    下面将用train_test_split方法来具体进行模型的选择\n\n'