## <font size=3>Fancy Indexing</font>

In [2]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
x[3]

3

In [4]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [6]:
'''
索引切片: 起点, 终点, 步长
'''
x[3:9:2]

array([3, 5, 7])

In [8]:
'''
如果我们要访问[3, 5, 8]

是否只能这么写呢?
'''
[x[3],x[5],x[8]]

[3, 5, 8]

In [9]:
'''
numpy给我们提供了新的方法: Fancy Indexing

ind: index的缩写

'''
ind = [3,5,8]

In [10]:
x[ind]

array([3, 5, 8])

In [11]:
'''
ind 也能是二维矩阵, 

x[ind] 索引值取出来的正是对应一维向量里面的值

'''
ind = np.array([[0, 2], [1, 3]])

x[ind]

array([[0, 2],
       [1, 3]])

In [12]:
'''
对二维矩阵进行fancy indexing

'''
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [14]:
X[0, col]

array([1, 2, 3])

In [15]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [16]:
'''
True False 的意思是对哪一列感兴趣

下面的例子就是说对0, 2, 3列的元素感兴趣
'''
col = [True, False, True, True]

In [18]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### <font size=3>numpy.array比较</font>

In [19]:
'''
我们经常要对表格中的数组进行批量式的比较, 返回的是布尔数组

'''
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
'''
什么意思? 就是将x中的所有元素与3进行比较,返回布尔值

'''
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [22]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [23]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [24]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [25]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [26]:
'''
同样这种比较也能作用在二维数组X上
'''
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
'''
这就是在numpy中进行universal的比较

'''
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [28]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
'''
这是将True当做了1, False当做了0
'''

np.sum(x <= 3)

4

In [32]:
'''
直接获得非零元素
'''
np.count_nonzero(x <= 3)

4

#### <font size=3>np.any</font>

In [31]:
'''
查看是否有 0 元素

np.any: 给定的布尔数组中, 有任意一个满足条件, 就返回True

'''
np.any(x == 0)

True

In [38]:
np.any(x < 0)

False

#### <font size=3>np.all</font>

In [36]:
np.all(x >= 0)

True

In [39]:
'''
了解是否存在某些数据, 存在某些性质

'''
np.all(x > 0)

False

In [40]:
'''
在二维数组下的操作
'''
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.sum(X % 2 == 0)

8

In [44]:
'''
一共有四行, 每一行都有两个偶数
'''
np.sum(X % 2 == 0, axis=1)

array([2, 2, 2, 2])

In [45]:
'''
第0列, 和第2列都是偶数
其余都是技术
'''
np.sum(X % 2 == 0, axis=0)

array([4, 0, 4, 0])

In [60]:
np.all(X>0, axis=1)

array([False,  True,  True,  True])

#### <font size=3>与或非操作</font>

In [55]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [56]:
x>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [53]:
'''
与运算: 

结果为6, 说明在x中有6个满足条件

注意到, 这里连接两个条件的符号不是 &&, 只有一个&, 相当于是一个 位运算符(and)

为什么是位运算符而不是条件运算符呢?

条件运算符连接的是两个条件, 也就是连接的是两个布尔值, 返回的结果也是一个布尔值

但是现在左侧和右侧分别是两个数组(数组里面都是True或者False)

在这里希望这两个数组按照响应的索引, 分别的进行与(and)或(or)的运算, 最后得到的结果依然是一个数组

那么这样的运算方式实际上是非常类似于 位运算 的

相当于这两个数组中, 每一个元素都被看作是 一位, 所以在这里我们要使用位运算符

'''  
np.sum((x > 3) & (x < 10))

6

In [54]:
'''
这里使用条件与算符的话, 最终的结果也是会报错的, 这不是一个合法的写法
'''
np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (<ipython-input-54-d834f65999a2>, line 1)

In [57]:
'''
或运算
'''
np.sum((x % 2 == 0) | (x > 10))

11

In [59]:
'''
非运算: ~
'''
np.sum(~(x == 0))

15

In [61]:
'''
比较运算符返回的布尔数组也可以作为fancy indexing

'''
x[x < 5]

array([0, 1, 2, 3, 4])

In [62]:
'''
年龄是偶数
''' 
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [64]:
'''
二维数组最后列特征值可以被3整除
'''
X[X[:, -1] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [ ]:
'''
Pandas对数据的处理非常优秀

而 sklearn 里面接收的都是numpy的数据, 所以我们一般使用pandas处理数据后转成numpy, 传给sklearn进行操作

'''