## <font size=3>聚合操作</font>

In [1]:
import numpy as np
L = np.random.random(100)

In [5]:
'''
一维数组
'''
L

array([0.09529284, 0.86478226, 0.28065171, 0.44200664, 0.6405873 ,
       0.40185248, 0.36345392, 0.67918378, 0.45252371, 0.26020171,
       0.30651625, 0.68851339, 0.03762224, 0.66124261, 0.60745585,
       0.76332241, 0.96447266, 0.59350497, 0.24542977, 0.01165098,
       0.33143163, 0.81450925, 0.85287433, 0.93285637, 0.3644724 ,
       0.62485633, 0.27504654, 0.91663811, 0.92951771, 0.17196657,
       0.88521168, 0.93076587, 0.83433352, 0.40667634, 0.69899675,
       0.59327353, 0.54667183, 0.72233688, 0.96272136, 0.73426978,
       0.1949282 , 0.12565879, 0.93399303, 0.35428519, 0.44147865,
       0.71381673, 0.69745054, 0.39601643, 0.07056716, 0.02252126,
       0.42757238, 0.69746177, 0.89277919, 0.45183574, 0.36250695,
       0.59215424, 0.22097672, 0.51023754, 0.54797373, 0.1028192 ,
       0.22639543, 0.26431926, 0.12836012, 0.59193195, 0.289345  ,
       0.07652446, 0.70021922, 0.66182301, 0.85745934, 0.76263281,
       0.33852665, 0.60390042, 0.79875107, 0.15984731, 0.79989

### <font size=3>python中的sum和np.sum的区别</font>

In [3]:
sum(L)

50.221984863260346

In [4]:
np.sum(L)

50.221984863260346

In [13]:
'''
很明显, np.sum的效率要远大于python sum

差距是100多倍
'''
big_array = np.random.rand(1000000)

In [20]:
%timeit sum(big_array)
%timeit np.sum(big_array)

130 ms ± 24.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.64 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### <font size=3>对于向量的聚合运算</font>

In [15]:
np.min(big_array)

1.1905002915701957e-06

In [16]:
np.max(big_array)

0.9999987166661043

In [17]:
'''
两种形式都能用, 随个人喜好
上面是np.func的形式使用方法, 这种会更全面, 而且代码比较清楚, 因为告诉别人我在用np这个库
下面是向量形式的使用方法
'''
big_array.min()

1.1905002915701957e-06

In [18]:
big_array.max()

0.9999987166661043

In [21]:
big_array.sum()

499302.5588877535

### <font size=3>对于二维矩阵的聚合运算</font>

In [33]:
X = np.arange(16).reshape((4, -1))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### <font size=3>np.sum</font>

In [25]:
'''
np聚合运算默认对不管是向量还是矩阵, 都是对所有的元素进行聚合
'''
np.sum(X)

120

In [30]:
'''
如果要计算每一行或者每一列的聚合运算

此处为什么axis=0是聚合列的运算呢?

    之前我们提过, axis就是沿着 某一维度 的意思
    axis = 0, 就是沿着行的方向, 也就是竖直方向, 也就是对每一列 逐行地 进行运算

'''
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [32]:
'''
axis = 1, 就是沿着列的方向进行运算, 也就是对每一行 逐列地 进行运算
'''
'''
记忆窍门:

我们可以想一下, 我们axis传的是什么值, 相当于把这个轴压缩掉, 不要这个轴

'''
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

#### <font size=3>np.prod: 所有元素乘积</font>

In [38]:
'''
返回所有元素相应的乘积
'''
np.prod(X)

0

In [39]:
'''
Python语言天然地支持大数运算, 不用担心整型溢出的问题
'''
np.prod(X + 1)

2004189184

#### <font size=3>np.mean: 平均值</font>

<font size=3>这里我们学初级统计的时候会知道, 初级统计...</font>

In [41]:
'''
平均值
'''
np.mean(X)

7.5

#### <font size=3>np.median: 中位数</font>

In [42]:
'''
中位数
'''
np.median(X)

7.5

In [43]:
'''
虽然我们会用均值来反映这组数据的整体情况, 但是对于和整体偏离太多的outerlier出界数据的话, 均值会显得非常敏感
'''
v = np.array([1,1,2,2,10])
np.mean(v)

3.2

In [46]:
'''
这时候现在中位数才能更好的代表整体的收入情况
'''
np.median(v)

2.0

#### <font size=3>np.percentile: 百分位数</font>
<font size=3>沿指定的轴计算数据的q百分位数。</font>


In [47]:
'''
意思是这组数据里面 50% 都是小于0.499的
'''
np.percentile(big_array, q=50)

0.49944378826713565

In [48]:
'''
你看吧, 其实这个值和中位数median求出来的是一个值

只不过有了百分位以后, 我们就可以对任意的百分位求值

'''
np.median(big_array)

0.49944378826713565

In [50]:
np.percentile(big_array, q=100)

0.9999987166661043

In [51]:
np.max(big_array)

0.9999987166661043

In [53]:
'''
在统计学上, 我们通常会对几个百分位点感兴趣
'''
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

1.1905002915701957e-06
0.24927036971267716
0.49944378826713565
0.7491719814054083
0.9999987166661043


#### <font size=3>np.var: 方差</font>

Variance: 方差

In [55]:
np.var(big_array)

0.08335843976774045

#### <font size=3>np.std: 标准差</font>

Standard deviation: 标准差

In [56]:
np.std(big_array)

0.28871861693998957

In [60]:
'''
正态分布: 均值为0, 标准差为1
''' 
x = np.random.normal(0, 1, size=1000000)

In [61]:
'''
均值趋近于0
'''
np.mean(x)

0.00031444638331054624

In [63]:
'''
标准差趋近于1
'''
np.std(x)

0.9995862322332788

## <font size=3>索引</font>

In [68]:
'''
这个数是正态分布的最小值, 但是这个值在哪儿呢?
'''
np.min(x)

-4.496054400401548

#### <font size=3>np.argmin</font>

In [66]:
'''

'''
np.argmin(x)

650057

In [67]:
'''
这样就找到了
'''
x[650057]

-4.496054400401548

#### <font size=3>np.argmax</font>

In [71]:
np.max(x)

5.0578171623204975

In [69]:
np.argmax(x)

796600

In [70]:
x[796600]

5.0578171623204975

## <font size=3>排序和使用索引</font>
#### <font size=3>对于向量的排序操作</font>

In [78]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### <font size=3>np.random.shuffle: 乱序</font>

In [84]:
np.random.shuffle(x)
x

array([ 6, 12,  0,  8,  2, 15,  7,  5, 13, 10,  1,  3,  9,  4, 11, 14])

#### <font size=3>np.sort</font>

In [80]:
'''
返回一个排好序的向量, 但并没有改变x本身
'''
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [81]:
'''
我们可以看到x并没有被 np.sort(x) 修改
'''
x

array([ 7, 11,  3,  0,  5,  6,  1,  9, 14, 13, 10,  2,  4, 12,  8, 15])

In [92]:
'''
x.sort(): 对x本身排序

区别于np.sort
'''
x.sort()

In [93]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### <font size=3>对于矩阵的排序操作</font>

In [86]:
X = np.random.randint(10, size=(4, 4))
X

array([[9, 8, 4, 2],
       [4, 0, 8, 1],
       [9, 8, 1, 3],
       [8, 0, 8, 0]])

In [88]:
'''
对每一行按照顺序进行排序
'''

np.sort(X)

array([[2, 4, 8, 9],
       [0, 1, 4, 8],
       [1, 3, 8, 9],
       [0, 0, 8, 8]])

In [89]:
'''
而且axis=1, 为什么是 1 ? 这个道理和之前聚合运算 axis 的道理是一样的

沿着列的方向, 就是把每一行编程有序的

'''

np.sort(X, axis=1)

array([[2, 4, 8, 9],
       [0, 1, 4, 8],
       [1, 3, 8, 9],
       [0, 0, 8, 8]])

In [90]:
'''
axis=0, 那么这就是沿着行进行排序, 那么这一列都是有序的
'''
np.sort(X, axis=0)

array([[4, 0, 1, 0],
       [8, 0, 4, 1],
       [9, 8, 8, 2],
       [9, 8, 8, 3]])

In [94]:
'''
另外, 在排序中也会使用索引
'''
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [95]:
np.random.shuffle(x)

In [98]:
x

array([15, 11,  1, 14, 12,  6,  9,  7,  0,  5, 13, 10,  3,  2,  8,  4])

#### <font size=3>np.argsort</font>

In [99]:
'''
argsort里面存的都是元素的索引, 比如下面第一小的元素(此处为0)的值是8, 对应原数组中0的索引值就是8, 以此类推

'''
np.argsort(x)

array([ 8,  2, 13, 12, 15,  9,  5,  7, 14,  6, 11,  1,  4, 10,  3,  0],
      dtype=int64)

#### <font size=3>np.partition</font>

<font size=3>有时候我们只要寻找比标定点小, 或者大的数, 那么只要对partition后的数组进行切片就可以了</font>

In [100]:
'''
对于排序算法来说, 快速排序有一个著名的子过程, 叫partition
partition: 寻找一个标定点, 小于标定点的数都放在这个标定点左边(不是有序的), 大于这个标定点的数都放在标定点右边 

np.partition(<向量>, <标定点>)

'''
np.partition(x, 3)

array([ 1,  0,  2,  3,  4,  6,  5,  7, 11,  9, 13, 10, 12, 14,  8, 15])

In [101]:
'''
返回对应的索引
'''
np.argpartition(x, 3)

array([ 2,  8, 13, 12, 15,  5,  9,  7,  1,  6, 10, 11,  4,  3, 14,  0],
      dtype=int64)

#### <font size=3>对于矩阵的arg索引操作</font>

In [102]:
X

array([[9, 8, 4, 2],
       [4, 0, 8, 1],
       [9, 8, 1, 3],
       [8, 0, 8, 0]])

In [104]:
'''
沿着列对行进行排序,
返回的是索引

'''
np.argsort(X, axis=1)

array([[3, 2, 1, 0],
       [1, 3, 0, 2],
       [2, 3, 1, 0],
       [1, 3, 0, 2]], dtype=int64)

In [107]:
np.argsort(X, axis=0)

array([[1, 1, 2, 3],
       [3, 3, 0, 1],
       [0, 0, 1, 0],
       [2, 2, 3, 2]], dtype=int64)

In [108]:
np.partition(X, 2, axis=1)

array([[2, 4, 8, 9],
       [0, 1, 4, 8],
       [1, 3, 8, 9],
       [0, 0, 8, 8]])

In [106]:
'''
看看这个索引矩阵对应原来的X为什么形成这样的结果

'''
np.argpartition(X, 2, axis=1)

array([[3, 2, 1, 0],
       [1, 3, 0, 2],
       [2, 3, 1, 0],
       [1, 3, 2, 0]], dtype=int64)

In [109]:
np.argpartition(X, 2, axis=0)

array([[1, 1, 2, 3],
       [3, 3, 0, 1],
       [2, 2, 1, 0],
       [0, 0, 3, 2]], dtype=int64)